### ISSUE TITLE
mysql_config not found

### ISSUE THREAD

**Issue by Mitalee** [dc740/django-coveragepy-github-action#3]
Hi,

would love to use this action. Currently seeing this error

```
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-91bjsonf/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-91bjsonf/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-91bjsonf/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------  
```

I would appreciate any suggestions.

**Comment by dc740** [comment]
It's supposed to run against a temporary Postgresql database, not MySql.
Yet that's not the problem. The problem is that the requirements.txt from your project is trying to install mysql. If you check the Dockerfile and entrypoint.sh files, you will find that these kind of packages often need extra setup and libraries. In your case it needs mysql_config to work. I'd suggest creating a new github action so you can modify the Dockerfile to also include it.
